/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { FederationWhereUniqueInput } from "../../federation/base/FederationWhereUniqueInput";
import { Type } from "class-transformer";
import { AssociationWhereUniqueInput } from "../../association/base/AssociationWhereUniqueInput";
import { AgenceWhereUniqueInput } from "../../agence/base/AgenceWhereUniqueInput";
import { UtilisateurWhereUniqueInput } from "../../utilisateur/base/UtilisateurWhereUniqueInput";

@InputType()
class StructureUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  code?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  affectationDomaine?: string | null;

  @ApiProperty({
    required: false,
    type: () => FederationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => FederationWhereUniqueInput)
  @IsOptional()
  @Field(() => FederationWhereUniqueInput, {
    nullable: true,
  })
  federation?: FederationWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => AssociationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AssociationWhereUniqueInput)
  @IsOptional()
  @Field(() => AssociationWhereUniqueInput, {
    nullable: true,
  })
  association?: AssociationWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => AgenceWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AgenceWhereUniqueInput)
  @IsOptional()
  @Field(() => AgenceWhereUniqueInput, {
    nullable: true,
  })
  agence?: AgenceWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  libelle?: string | null;

  @ApiProperty({
    required: false,
    type: () => UtilisateurWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UtilisateurWhereUniqueInput)
  @IsOptional()
  @Field(() => UtilisateurWhereUniqueInput, {
    nullable: true,
  })
  utilisateur?: UtilisateurWhereUniqueInput | null;
}

export { StructureUpdateInput as StructureUpdateInput };
