/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { EnumStructureTypeField } from "./EnumStructureTypeField";
import { EnumStructureTypeFieldCountArgs } from "./EnumStructureTypeFieldCountArgs";
import { EnumStructureTypeFieldFindManyArgs } from "./EnumStructureTypeFieldFindManyArgs";
import { EnumStructureTypeFieldFindUniqueArgs } from "./EnumStructureTypeFieldFindUniqueArgs";
import { DeleteEnumStructureTypeFieldArgs } from "./DeleteEnumStructureTypeFieldArgs";
import { EnumStructureTypeFieldService } from "../enumStructureTypeField.service";
@graphql.Resolver(() => EnumStructureTypeField)
export class EnumStructureTypeFieldResolverBase {
  constructor(protected readonly service: EnumStructureTypeFieldService) {}

  async _enumStructureTypeFieldsMeta(
    @graphql.Args() args: EnumStructureTypeFieldCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [EnumStructureTypeField])
  async enumStructureTypeFields(
    @graphql.Args() args: EnumStructureTypeFieldFindManyArgs
  ): Promise<EnumStructureTypeField[]> {
    return this.service.enumStructureTypeFields(args);
  }

  @graphql.Query(() => EnumStructureTypeField, { nullable: true })
  async enumStructureTypeField(
    @graphql.Args() args: EnumStructureTypeFieldFindUniqueArgs
  ): Promise<EnumStructureTypeField | null> {
    const result = await this.service.enumStructureTypeField(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => EnumStructureTypeField)
  async deleteEnumStructureTypeField(
    @graphql.Args() args: DeleteEnumStructureTypeFieldArgs
  ): Promise<EnumStructureTypeField | null> {
    try {
      return await this.service.deleteEnumStructureTypeField(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
